shortcuts = {
    'ROFL': 'Rolling On The Floor Laughing',
    'STFU': 'Shut the f*** up',
    'ICYMI': 'In case you missed it',
    'TL;DR': 'Too long, didn’t read',
    'TMI': 'Too much information',
    'AFAIK': 'As Far As I Know',
    'LMK': 'Let me know',
    'NVM': 'Nevermind',
    'FTW': 'For the win',
    'BYOB': 'Bring your own beer',
    'BOGO': 'Buy one get one',
    'JK': 'Just kidding',
    'JW': 'Just wondering',
    'TGIF': 'Thank goodness it’s Friday',
    'TBH': 'To be honest',
    'TBF': 'To be frank',
    'RN': 'Right now',
    'FUBAR': 'F***** up beyond all recognition',
    'BRB': 'Be Right Back',
    'ISO': 'In search of',
    'BRT': 'Be Right There',
    'BTW': 'By The Way',
    'FTFY': 'Fixed that for you',
    'GG': 'Good Game',
    'BFD': 'Big freaking deal',
    'IRL': 'In Real Life',
    'DAE': 'Does anyone else?',
    'LOL': 'Laughing Out Loud',
    'SMH': 'Shaking My Head',
    'NGL': 'Not gonna lie',
    'BTS': 'Behind the scenes',
    'IKR': 'I Know Right',
    'TTYL': 'Talk to you later',
    'HMU': 'Hit me up',
    'FWIW': 'For what it’s worth',
    'IMO': 'In my opinion',
    'WYD': 'What are you doing?',
    'IMHO': 'In my humble opinion',
    'IDK': 'I Don’t Know',
    'IDC': 'I Don’t Care',
    'IDGAF': 'I don’t give a f***',
    'NBD': 'No big deal',
    'TBA': 'To be announced',
    'TBD': 'To be decided',
    'AFK': 'Away From Keyboard',
    'ABT': 'About',
    'IYKYK': 'If You Know You Know',
    'B4': 'Before',
    'BC': 'Because',
    'JIC': 'Just In Case',
    'FOMO': 'Fear Of Missing Out',
    'SNAFU': 'Situation Normal, All F***** Up',
    'GTG/G2G': 'Got To Go',
    'H8': 'Hate',
    'LMAO': 'Laughing My A** Off',
    'IYKWIM': 'If You Know What I Mean',
    'MYOB': 'Mind Your Own Business',
    'POV': 'Point Of View',
    'TLC': 'Tender Loving Care',
    'HBD': 'Happy Birthday',
    'W/E': 'Whatever',
    'WTF': 'What The F***',
    'WYSIWYG': 'What You See Is What You Get',
    'FWIF': 'For What It’s Worth',
    'TW': 'Trigger Warning',
    'EOD': 'End Of Day',
    'FAQ': 'Frequently Asked Question',
    'AKA': 'Also Known As',
    'ASAP': 'As Soon As Possible',
    'DIY': 'Do It Yourself',
    'LMGTFY': 'Let Me Google That For You',
    'NP': 'No Problem',
    'N/A': 'Not Applicable Or Not Available',
    'OOO': 'Out Of Office',
    'TIA': 'Thanks In Advance',
    'COB': 'Close Of Business',
    'FYI': 'For Your Information',
    'NSFW': 'Not Safe For Work',
    'WFH': 'Work From Home',
    'OMW': 'On My Way',
    'WDYT': 'What Do You Think?',
    'WYGAM': 'When You Get A Minute',
    'SMP': 'Social Media Platform',
    'DM': 'Direct Message',
    'FB': 'Facebook',
    'IG': 'Instagram',
    'LI': 'LinkedIn',
    'YT': 'YouTube',
    'SC': 'Snapchat',
    'BR': 'BeReal',
    'X': 'Previously Named Twitter',
    'WA': 'WhatsApp',
    'TT': 'TikTok',
    'FF': 'Follow Friday',
    'IM': 'Instant Message',
    'PM': 'Private Message',
    'OP': 'Original Post',
    'QOTD': 'Quote Of The Day',
    'OOTD': 'Outfit Of The Day',
    'RT': 'Retweet',
    'TBT': 'Throwback Thursday',
    'TIL': 'Today I Learned',
    'AMA': 'Ask Me Anything',
    'ELI5': 'Explain Like I’m 5',
    'FBF': 'Flashback Friday',
    'MFW': 'My Feeling When',
    'HMU': 'Hit Me Up',
    'GRWM': 'Get Ready With Me',
    'ILY': 'I Love You',
    'MCM': 'Man Crush Monday',
    'WCW': 'Woman Crush Wednesday',
    'BF': 'Boyfriend',
    'GF': 'Girlfriend',
    'LYSM': 'Love You So Much',
    'PDA': 'Public Display Of Affection',
    'LTR': 'Longterm Relationship',
    'DTR': 'Define The Relationship',
    'LDR': 'Long Distance Relationship',
    'XOXO': 'Hugs And Kisses',
    'OTP': 'One True Pairing',
    'LOML': 'Love Of My Life',
    'ATK': 'At The Keyboard',
    'ATM': 'At The Moment',
    'A3': 'Anytime, Anywhere, Anyplace',
    'BAK': 'Back At Keyboard',
    'BBL': 'Be Back Later',
    'BBS': 'Be Back Soon',
    'BFN': 'Bye For Now',
    'B4N': 'Bye For Now',
    'CU': 'See You',
    'CUL8R': 'See You Later',
    'CYA': 'See You',
    'FC': 'Fingers Crossed',
    'GAL': 'Get A Life',
    'GN': 'Good Night',
    'GMTA': 'Great Minds Think Alike',
    'GR8': 'Great!',
    'G9': 'Genius',
    'IC': 'I See',
    'ICQ': 'I Seek You (Also A Chat Program)',
    'ILU': 'I Love You',
    'IOW': 'In Other Words',
    'KISS': 'Keep It Simple, Stupid',
    'LTNS': 'Long Time No See',
    'L8R': 'Later',
    'MTE': 'My Thoughts Exactly',
    'M8': 'Mate',
    'NRN': 'No Reply Necessary',
    'OIC': 'Oh I See',
    'PITA': 'Pain In The A..',
    'PRT': 'Party',
    'PRW': 'Parents Are Watching',
    'QPSA?': 'Que Pasa?',
    'ROFLOL': 'Rolling On The Floor Laughing Out Loud',
    'ROTFLMAO': 'Rolling On The Floor Laughing My A** Off',
    'SK8': 'Skate',
    'STATS': 'Your Sex And Age',
    'ASL': 'Age, Sex, Location',
    'THX': 'Thank You',
    'TTFN': 'Ta-Ta For Now!',
    'U': 'You',
    'U2': 'You Too',
    'U4E': 'Yours For Ever',
    'WB': 'Welcome Back',
    'WTF': 'What The F***',
    'WTG': 'Way To Go!',
    'WUF': 'Where Are You From?',
    'W8': 'Wait...',
    '7K': 'Sick:-D Laugher',
    'TFW': 'That Feeling When',
    'MFW': 'My Face When',
    'MRW': 'My Reaction When',
    'IFYP': 'I Feel Your Pain',
    'TNTL': 'Trying Not To Laugh',
    'IMU': 'I Miss You',
    'ADIH': 'Another Day In Hell',
    'ZZZ': 'Sleeping, Bored, Tired',
    'WYWH': 'Wish You Were Here',
    'FIMH': 'Forever In My Heart',
    'BSAAW': 'Big Smile And A Wink',
    'BWL': 'Bursting With Laughter',
    'BFF': 'Best Friends Forever',
    'CSL': "Can't Stop Laughing",
    'OMG': "Oh my Good",
    'UR': "You are",
    "isn't": "is not",
    "he's": "he is",
    "wasn't": "was not",
    "there's": "there is",
    "couldn't": "could not",
    "won't": "will not",
    "they're": "they are",
    "she's": "she is",
    "There's": "there is",
    "wouldn't": "would not",
    "haven't": "have not",
    "That's": "That is",
    "you've": "you have",
    "He's": "He is",
    "what's": "what is",
    "weren't": "were not",
    "we're": "we are",
    "hasn't": "has not",
    "you'd": "you would",
    "shouldn't": "should not",
    "let's": "let us",
    "they've": "they have",
    "You'll": "You will",
    "i'm": "I am",
    "i´m": "I am",
    "we've": "we have",
    "it's": "it is",
    "don't": "do not",
    "that´s": "that is",
    "I´m": "I am",
    "it’s": "it is",
    "she´s": "she is",
    "he’s'": "he is",
    "I’m": "I am",
    "I’d": "I did",
    "he’s'": "he is",
    "there’s": "there is",
    "can't": "can not"
}

# https://github.com/charlesmalafosse/FastText-sentiment-analysis-for-tweets/blob/master/betsentiment_sentiment_analysis_fasttext.py
shortforms = {
    "isn't": 'is not',
    "he's": 'he is',
    "wasn't": 'was not',
    "there's": 'there is',
    "couldn't": 'could not',
    "won't": 'will not',
    "they're": 'they are',
    "she's": 'she is',
    "There's": 'there is',
    "wouldn't": 'would not',
    "haven't": 'have not',
    "That's": 'That is',
    "you've": 'you have',
    "He's": 'He is',
    "what's": 'what is',
    "weren't": 'were not',
    "we're": 'we are',
    "hasn't": 'has not',
    "you'd": 'you would',
    "shouldn't": 'should not',
    "let's": 'let us',
    "they've": 'they have',
    "You'll": 'You will',
    "i'm": 'i am',
    "we've": 'we have',
    "it's": 'it is',
    "don't": 'do not',
    "that´s": 'that is',
    "I´m": 'I am',
    "it’s": 'it is',
    "she´s": 'she is',
    "he’s'": 'he is',
    "I’m": 'I am',
    "I’d": 'I did',
    "there’s": 'there is',
}

smileys = {
    ":‑)": "smiley",
    ":-]": "smiley",
    ":-3": "smiley",
    ":->": "smiley",
    "8-)": "smiley",
    ":-}": "smiley",
    ":)": "smiley",
    ":]": "smiley",
    ":3": "smiley",
    ":>": "smiley",
    "8)": "smiley",
    ":}": "smiley",
    ":o)": "smiley",
    ":c)": "smiley",
    ":^)": "smiley",
    "=]": "smiley",
    "=)": "smiley",
    ":-))": "smiley",
    ":‑D": "smiley",
    "8‑D": "smiley",
    "x‑D": "smiley",
    "X‑D": "smiley",
    ":D": "smiley",
    "8D": "smiley",
    "xD": "smiley",
    "XD": "smiley",
    ":‑(": "sad",
    ":‑c": "sad",
    ":‑<": "sad",
    ":‑[": "sad",
    ":(": "sad",
    ":c": "sad",
    ":<": "sad",
    ":[": "sad",
    ":-||": "sad",
    ">:[": "sad",
    ":{": "sad",
    ":@": "sad",
    ">:(": "sad",
    ":'‑(": "sad",
    ":'(": "sad",
    ":‑P": "playful",
    "X‑P": "playful",
    "x‑p": "playful",
    ":‑p": "playful",
    ":‑Þ": "playful",
    ":‑þ": "playful",
    ":‑b": "playful",
    ":P": "playful",
    "XP": "playful",
    "xp": "playful",
    ":p": "playful",
    ":Þ": "playful",
    ":þ": "playful",
    ":b": "playful",
    "<3": "love"
}
symbol_mapping = {
    "⇨": "rightwards arrow",
    "➪": "rightwards arrow",
    "→": "rightwards arrow",
    "←": "leftwards arrow",
    "↔": "left-right arrow",
    "↕": "up-down arrow",
    "✓": "check mark",
    "✔": "bold check mark",
    "✗": "cross mark",
    "✘": "bold cross mark",
    "★": "star",
    "☆": "white star",
    "❤": "heart",
    "💔": "broken heart",
    "♦": "diamond",
    "🔷": "large blue diamond",
    "🔶": "large orange diamond",
    "👉": "pointing right",
    "👈": "pointing left",
    "👇": "pointing down",
    "👆": "pointing up",
    "⚠": "warning sign",
    "❗": "exclamation mark",
    "ℹ": "information sign",
    "⏰": "alarm clock",
    "📅": "calendar",
    "$": "dollar sign",
    "€": "euro sign",
    "💰": "money bag",
}
